//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorEmployee
    {
        public int EmployeeJobID { get; set; }
        public Nullable<int> ContractorID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
