//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor1
    {
        public int Id { get; set; }
        public int AddressID { get; set; }
        public string Name { get; set; }
        public string EmailID { get; set; }
        public string ContactPerson { get; set; }
        public int ContactNo { get; set; }
        public string ABN { get; set; }
        public int PaymentOption { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
