//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KiaOraEntities : DbContext
    {
        public KiaOraEntities()
            : base("name=KiaOraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Address1> Addresses1 { get; set; }
        public virtual DbSet<ApproveGroup> ApproveGroups { get; set; }
        public virtual DbSet<ApproveGroup1> ApproveGroups1 { get; set; }
        public virtual DbSet<ApproveGroupUser> ApproveGroupUsers { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<ContractorEmployee> ContractorEmployees { get; set; }
        public virtual DbSet<Contractor1> Contractors1 { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee1> Employees1 { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentCategory> EquipmentCategories { get; set; }
        public virtual DbSet<EquipmentCategory1> EquipmentCategories1 { get; set; }
        public virtual DbSet<Equipment1> Equipments1 { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobEmployee> JobEmployees { get; set; }
        public virtual DbSet<JobEquipment> JobEquipments { get; set; }
        public virtual DbSet<JobEquipment1> JobEquipments1 { get; set; }
        public virtual DbSet<Job1> Jobs1 { get; set; }
        public virtual DbSet<RequestHeader> RequestHeaders { get; set; }
        public virtual DbSet<RequestHeader1> RequestHeaders1 { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Site1> Sites1 { get; set; }
        public virtual DbSet<SiteSubContractor> SiteSubContractors { get; set; }
        public virtual DbSet<SiteSubContractor1> SiteSubContractors1 { get; set; }
        public virtual DbSet<SubContractor> SubContractors { get; set; }
        public virtual DbSet<SubContractor1> SubContractors1 { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<WorkType> WorkTypes { get; set; }
        public virtual DbSet<WorkType1> WorkTypes1 { get; set; }
    }
}
