//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site1
    {
        public int Id { get; set; }
        public int WorkTypeID { get; set; }
        public int AddressID { get; set; }
        public int ContractorID { get; set; }
        public string SiteName { get; set; }
        public int WorkType { get; set; }
        public string Notes { get; set; }
        public int Budget { get; set; }
        public int Allocation { get; set; }
        public int WorkDays { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
