//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.Jobs = new HashSet<Job>();
            this.SiteSubContractors = new HashSet<SiteSubContractor>();
        }
    
        public int ID { get; set; }
        public int WorkTypeID { get; set; }
        public int AddressID { get; set; }
        public int ContractorID { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> WorkType { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<int> Allocation { get; set; }
        public Nullable<int> WorkDays { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contractor Contractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteSubContractor> SiteSubContractors { get; set; }
        public virtual WorkType WorkType1 { get; set; }
    }
}
