//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHeader
    {
        public int ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public int GroupID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int JobID { get; set; }
        public Nullable<System.DateTime> RequestDateTime { get; set; }
        public Nullable<int> ApproveGroupID { get; set; }
        public string ApproveStatus { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ApproveGroup ApproveGroup { get; set; }
        public virtual Job Job { get; set; }
    }
}
