//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubContractor
    {
        public int ID { get; set; }
        public int ContractorID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string ABN { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Contractor Contractor { get; set; }
    }
}
